# Mod 9 CS III

In [1]:
#Importing necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
#import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
"""1.Load the data from “college.csv” that has attributes collected about private and public colleges for a particular year.
We will try to predict the private/public status of the college from other attributes."""

#Loading the dataset
data = pd.read_csv("College.csv", header=0)
data.shape

(777, 18)

In [3]:
data.head()

,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
0,Yes,1660,1232,721,23,52,2885,537,7440,3300,450,2200,70,78,18.1,12,7041,60
1,Yes,2186,1924,512,16,29,2683,1227,12280,6450,750,1500,29,30,12.2,16,10527,56
2,Yes,1428,1097,336,22,50,1036,99,11250,3750,400,1165,53,66,12.9,30,8735,54
3,Yes,417,349,137,60,89,510,63,12960,5450,450,875,92,97,7.7,37,19016,59
4,Yes,193,146,55,16,44,249,869,7560,4120,800,1500,76,72,11.9,2,10922,15

In [4]:
#listing columns 
data.columns

Index(['Private', 'Apps', 'Accept', 'Enroll', 'Top10perc', 'Top25perc',
       'F.Undergrad', 'P.Undergrad', 'Outstate', 'Room.Board', 'Books',
       'Personal', 'PhD', 'Terminal', 'S.F.Ratio', 'perc.alumni', 'Expend',
       'Grad.Rate'],
      dtype='object')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 777 entries, 0 to 776
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Private      777 non-null    object
 1   Apps         777 non-null    int64
 2   Accept       777 non-null    int64
 3   Enroll       777 non-null    int64
 4   Top10perc    777 non-null    int64
 5   Top25perc    777 non-null    int64
 6   F.Undergrad  777 non-null    int64
 7   P.Undergrad  777 non-null    int64
 8   Outstate     777 non-null    int64
 9   Room.Board   777 non-null    int64
 10  Books        777 non-null    int64
 11  Personal     777 non-null    int64
 12  PhD          777 non-null    int64
 13  Terminal     777 non-null    int64
 14  S.F.Ratio    777 non-null    float64
 15  perc.alumni  777 non-null    int64
 16  Expend       777 non-null    int64
 17  Grad.Rate    777 non-null    int64
dtypes: float64(1), int64(16), object(1)
memory usage: 109.4+ KB

In [6]:
data.describe()

,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
count,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.00000
mean,3001.638353,2018.804376,779.972973,27.558559,55.796654,3699.907336,855.298584,10440.669241,4357.526384,549.380952,1340.642214,72.660232,79.702703,14.089704,22.743887,9660.171171,65.46332
std,3870.201484,2451.113971,929.176190,17.640364,19.804778,4850.420531,1522.431887,4023.016484,1096.696416,165.105360,677.071454,16.328155,14.722359,3.958349,12.391801,5221.768440,17.17771
min,81.000000,72.000000,35.000000,1.000000,9.000000,139.000000,1.000000,2340.000000,1780.000000,96.000000,250.000000,8.000000,24.000000,2.500000,0.000000,3186.000000,10.00000
25%,776.000000,604.000000,242.000000,15.000000,41.000000,992.000000,95.000000,7320.000000,3597.000000,470.000000,850.000000,62.000000,71.000000,11.500000,13.000000,6751.000000,53.00000
50%,1558.000000,1110.000000,434.000000,23.000000,54.000000,1707.000000,353.000000,9990.000000,4200.000000,500.000000,1200.000000,75.000000,82.000000,13.600000,21.000000,8377.000000,65.00000
75%,3624.000000,2424.000000,902.000000,35.000000,69.000000,4005.000000,967.000000,12925.000000,5050.000000,600.000000,1700.000000,85.000000,92.000000,16.500000,31.000000,10830.000000,78.00000
max,48094.000000,26330.000000,6392.000000,96.000000,100.000000,31643.000000,21836.000000,21700.000000,8124.000000,2340.000000,6800.000000,103.000000,100.000000,39.800000,64.000000,56233.000000,118.00000

In [7]:
#Feature Variable (Assigning all the columns except the target variable)
X = data.drop(["Private"], axis=1)
X.head()

,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
0,1660,1232,721,23,52,2885,537,7440,3300,450,2200,70,78,18.1,12,7041,60
1,2186,1924,512,16,29,2683,1227,12280,6450,750,1500,29,30,12.2,16,10527,56
2,1428,1097,336,22,50,1036,99,11250,3750,400,1165,53,66,12.9,30,8735,54
3,417,349,137,60,89,510,63,12960,5450,450,875,92,97,7.7,37,19016,59
4,193,146,55,16,44,249,869,7560,4120,800,1500,76,72,11.9,2,10922,15

In [8]:
#Target Variable
y = data.Private
y.head()

0    Yes
1    Yes
2    Yes
3    Yes
4    Yes
Name: Private, dtype: object

In [9]:
"""2. Use LabelEncoder to encode the target variable in to numerical form and 
split the data such that 20% of the data is set aside for testing."""

#Encoding the tagert variable
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(y)
print(integer_encoded)
# invert first example
inverted = label_encoder.inverse_transform([np.argmax(integer_encoded[:])])
print(inverted)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 0 1 0 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 0 1 1 0 0 1 1 1
 1 1 1 1 1 1 1 0 1 1 0 1 0 1 1 1 0 1 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1
 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 0 1 1 1 1 1
 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 1 0 0 1 1 1 1 1 1 1
 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 0 0 0 1 0
 1 1 1 1 1 0 0 0 1 1 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0
 1 1 1 0 0 0 1 1 0 1 0 1 0 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1
 0 0 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 0 0 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1
 1 1 0 1 1 1 1 1 1 1 1 0 0 0 1 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1
 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0
 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 1 1 0 0 1 1 1 1 1 1 1 0 0 1 0 0 0 1 0 1 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1
 1 0 1 1 1 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 1 0 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0
 1 0 1 0 1 0 0 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1 1]
['No']

In [10]:
"""3. Fit a linear svm from scikit learn and observe the accuracy.
[Hint: Use Linear SVC]"""

def linearSVC(X, integer_encoded):
    
     #Splitting the data in train-test with 20% of the data kept aside for testing.
    from sklearn.model_selection import train_test_split
    X_train, X_test, y_train, y_test = train_test_split(X, integer_encoded, test_size=0.2, random_state=30)
    print(f"Splitting the data with test-size as 20% and random state as 30")

    from sklearn.svm import LinearSVC
    clf_linSVC = LinearSVC()
    clf_linSVC = clf_linSVC.fit(X_train, y_train)

    #Predicting the data
    y_pred = clf_linSVC.predict(X_test)

    import sklearn.metrics as metrics
    score_SVC = metrics.accuracy_score(y_pred, y_test)
    print(f"The Accuracy score with the SVC classifier is : {score_SVC}")

    #Printing the Confusion matrix for the SVC classifier
    cls_SVC = metrics.confusion_matrix(y_pred, y_test)
    print(f"Confusion matrix with the SVC classifier is: \n{cls_SVC}")
    
    #Printing the Classification report for the SVC classifier
    cls_SVC = metrics.classification_report(y_pred, y_test)
    print(f"Classification report with the SVC classifier is: \n{cls_SVC}")
    print('*'*40)

In [11]:
print("Predicting values using the SVC classifier")
linearSVC(X, integer_encoded)

Predicting values using the SVC classifier
Splitting the data with test-size as 20% and random state as 30
The Accuracy score with the SVC classifier is : 0.8910256410256411
Confusion matrix with the SVC classifier is:
[[ 31   1]
 [ 16 108]]
Classification report with the SVC classifier is:
              precision    recall  f1-score   support

           0       0.66      0.97      0.78        32
           1       0.99      0.87      0.93       124

    accuracy                           0.89       156
   macro avg       0.83      0.92      0.86       156
weighted avg       0.92      0.89      0.90       156

****************************************

/srv/conda/envs/notebook/lib/python3.6/site-packages/sklearn/svm/_base.py:986: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

In [12]:
"""4. Preprocess the data using StandardScalar and fit the same model again and observe the change in accuracy.
[Hint: Refer to scikitlearn’s preprocessing methods]"""

from sklearn.preprocessing import StandardScaler
scaled = StandardScaler().fit_transform(X) 
scaled_df = pd.DataFrame(scaled, columns = X.columns)
scaled_df.head()

,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
0,-0.346882,-0.321205,-0.063509,-0.258583,-0.191827,-0.168116,-0.209207,-0.746356,-0.964905,-0.602312,1.270045,-0.163028,-0.115729,1.013776,-0.867574,-0.501910,-0.318252
1,-0.210884,-0.038703,-0.288584,-0.655656,-1.353911,-0.209788,0.244307,0.457496,1.909208,1.215880,0.235515,-2.675646,-3.378176,-0.477704,-0.544572,0.166110,-0.551262
2,-0.406866,-0.376318,-0.478121,-0.315307,-0.292878,-0.549565,-0.497090,0.201305,-0.554317,-0.905344,-0.259582,-1.204845,-0.931341,-0.300749,0.585935,-0.177290,-0.667767
3,-0.668261,-0.681682,-0.692427,1.840231,1.677612,-0.658079,-0.520752,0.626633,0.996791,-0.602312,-0.688173,1.185206,1.175657,-1.615274,1.151188,1.792851,-0.376504
4,-0.726176,-0.764555,-0.780735,-0.655656,-0.596031,-0.711924,0.009005,-0.716508,-0.216723,1.518912,0.235515,0.204672,-0.523535,-0.553542,-1.675079,0.241803,-2.939613

In [13]:
print("Predicting values using the SVC classifier after StandardScalar normalization")
linearSVC(scaled_df, integer_encoded)

Predicting values using the SVC classifier after StandardScalar normalization
Splitting the data with test-size as 20% and random state as 30
The Accuracy score with the SVC classifier is : 0.9294871794871795
Confusion matrix with the SVC classifier is:
[[ 38   2]
 [  9 107]]
Classification report with the SVC classifier is:
              precision    recall  f1-score   support

           0       0.81      0.95      0.87        40
           1       0.98      0.92      0.95       116

    accuracy                           0.93       156
   macro avg       0.90      0.94      0.91       156
weighted avg       0.94      0.93      0.93       156

****************************************

/srv/conda/envs/notebook/lib/python3.6/site-packages/sklearn/svm/_base.py:986: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

In [14]:
"""5. Use scikit learn’s gridsearch to select the best hyperparameter for a non-linear SVM, 
identify the model with best score and its parameters.
[Hint: Refer to model_selection module of Scikit learn]"""

#Splitting the data in train-test with 20% of the data kept aside for testing.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, integer_encoded, test_size=0.2, random_state=30)
print(f"Splitting the data with test-size as 20% and random state as 30")

from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

parameter_candidates = [
 # {'C': [1, 10, 100, 1000], 'kernel': ['linear']},
  {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf', 'sigmoid']},
]

# Create a classifier object with the classifier and parameter candidates
clf_grid = GridSearchCV(estimator=SVC(), param_grid=parameter_candidates, n_jobs=-1)

# Train the classifier 
clf_grid = clf_grid.fit(X_train, y_train)
print(f"{parameter_candidates}")

Splitting the data with test-size as 20% and random state as 30
[{'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf', 'sigmoid']}]

In [15]:
# # Note: Not using the Linear kernel as it is not responding. (Could be computationally inefficient)

In [16]:
# View the accuracy score
print('Best score for data1:', clf_grid.best_score_)

Best score for data1: 0.7342967741935483

In [17]:
# View the best parameters for the model found using grid search
print('Best C:',clf_grid.best_estimator_.C) 
print('Best Kernel:',clf_grid.best_estimator_.kernel)
print('Best Gamma:',clf_grid.best_estimator_.gamma)

Best C: 1
Best Kernel: rbf
Best Gamma: 0.001

In [18]:
# Note: Using the LinearSVC algo as it was not working in the previous estimation

#Splitting the data in train-test with 20% of the data kept aside for testing.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, integer_encoded, test_size=0.2, random_state=30)
print(f"Splitting the data with test-size as 20% and random state as 30")

from sklearn.model_selection import GridSearchCV
from sklearn.svm import LinearSVC

parameter_candidates = [
  {'C': [1, 10, 100, 1000]}
]

# Create a classifier object with the classifier and parameter candidates
clf_grid = GridSearchCV(estimator=LinearSVC(), param_grid=parameter_candidates, n_jobs=-1)

# Train the classifier 
clf_grid = clf_grid.fit(X_train, y_train)
print(f"{parameter_candidates}")

Splitting the data with test-size as 20% and random state as 30
[{'C': [1, 10, 100, 1000]}]

/srv/conda/envs/notebook/lib/python3.6/site-packages/sklearn/svm/_base.py:986: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

In [19]:
# View the best parameters for the model found using grid search
print("Best score for a Linear SVM with the GridSerach CV", clf_grid.best_score_)
print('Best C:',clf_grid.best_estimator_.C)

Best score for a Linear SVM with the GridSerach CV 0.9002193548387097
Best C: 1

In [20]:
#Predicting the model and view the accuracy with the best parameters predicted - 
#Best C: 1
#Best Kernel: rbf
#Best Gamma: 0.001

from sklearn.svm import SVC
clf_SVC = SVC(C=1, kernel='rbf', gamma=0.001)
clf_SVC = clf_SVC.fit(X_train, y_train)

#Predicting the data
y_pred = clf_SVC.predict(X_test)


import sklearn.metrics as metrics
score_SVC = metrics.accuracy_score(y_pred, y_test)
print(f"The Accuracy score with the SVC classifier is : {score_SVC}")

#Printing the Confusion matrix for the SVC classifier
cls_SVC = metrics.confusion_matrix(y_pred, y_test)
print(f"Confusion matrix with the SVC classifier is: \n{cls_SVC}")

#Printing the Classification report for the SVC classifier
cls_SVC = metrics.classification_report(y_pred, y_test)
print(f"Classification report with the SVC classifier is: \n{cls_SVC}")
print('*'*40)

The Accuracy score with the SVC classifier is : 0.6987179487179487
Confusion matrix with the SVC classifier is:
[[  0   0]
 [ 47 109]]
Classification report with the SVC classifier is:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.70      0.82       156

    accuracy                           0.70       156
   macro avg       0.50      0.35      0.41       156
weighted avg       1.00      0.70      0.82       156

****************************************

/srv/conda/envs/notebook/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/srv/conda/envs/notebook/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/srv/conda/envs/notebook/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))